app/questions/forms.py
from flask.ext.wtf.file import FileField
from flask.ext.wtf.form import Form
from wtforms.fields.simple import SubmitField
from wtforms.validators import DataRequired

__author__ = 'Girish'


class SubmitForm(Form):
    code = FileField("Your code", validators=[DataRequired()])
    submit = SubmitField("Upload Code")


class TestForm(Form):
    test = FileField("Your Test output:", validators=[DataRequired()])
    test_submit = SubmitField("Upload Test")



app/__init__.py
from flask.ext.admin.base import Admin
from flask.ext.admin.contrib.sqla.view import ModelView
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager

from config import config




# from app.questions.model import Question,TestCase

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_view = 'auth.login'
from app.auth.model import User
from app.questions.model import Question, TestCase, Submission
from app.model.modelViewSecure import SecureView

def create_app(config_name):
    app = Flask(__name__)

    bootstrap.init_app(app)
    db.init_app(app)
    admin = Admin(app)
    admin.add_view(SecureView(User, db.session))
    admin.add_view(SecureView(Question, db.session))
    admin.add_view(SecureView(TestCase, db.session))
    admin.add_view(SecureView(Submission, db.session))
    app.config.from_object(config[config_name])
    from app.auth import auth as auth_blueprint

    app.register_blueprint(auth_blueprint, url_prefix='/auth')
    from app.questions import questions as questions_blueprint

    app.register_blueprint(questions_blueprint, url_prefix="")
    login_manager.init_app(app)
    return app

app/compiler/__init__.py
__author__ = 'Girish'

app/questions/__init__.py
__author__ = 'Girish'
from flask import Blueprint

questions = Blueprint("questions", __name__)
from app.questions import routes

app/questions/routes.py
import os
import time
from multiprocessing import Process, Queue

from sqlalchemy import desc
from flask.ext.login import current_user, login_required
from flask.globals import request
from flask.helpers import flash, url_for
from flask import redirect
from sqlalchemy.sql import functions

from app.auth.model import User
from app.questions.forms import SubmitForm, TestForm
from app import db


__author__ = 'Girish'
from flask import render_template
from app.questions import questions
from app.questions.model import Question, Submission

ALLOWED_EXTENSIONS = {'c', 'cpp', 'py', 'rb', 'java', 'txt'}
UPLOAD_LOCATION = os.path.abspath("app/static/upload")
TEST_LOCATION = os.path.abspath("app/static/tests")


@questions.route("/")
def index():
    if current_user.is_authenticated:
        all_questions = Question.query.all()
        all_submissions = db.session.query(Submission.question_id,functions.max(Submission.result_score),Submission.result_message,Submission.result).filter(Submission.user_id==current_user.id).group_by(
            Submission.question_id,Submission.result_message,Submission.result).all()
        return render_template("index.html", all_quest=all_questions,allsubmission =all_submissions)
    flash("you need to login to see the questions", category="warning")
    return redirect(url_for("auth.login"))


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS


@questions.route("/questions/<int:id>")
@login_required
def getquestion(id):
    selected_question = Question.query.filter(Question.id == id).first()
    filename = selected_question.testcases[0].input_test
    submitform = SubmitForm()
    testform = TestForm()
    selected_question = Question.query.filter(Question.id == id).first()
    return render_template("question.html", question=selected_question, form=submitform, test_form=testform,file_name=filename)


def find_score(filename, id, userid):
    """
    the import here is done inside because else a cyclic import situation arrises but as this
    method runs inside another process so the time consumed doesnt matter
    :param filename:
    :param id:
    :return:
    """
    from manage import app

    with app.app_context():
        with open(filename) as file:
            length = len(file.read())
        question = Question.query.filter(Question.id == id).first()
        maxS = question.max_score
        print(length, maxS)
        score = ((maxS - length) / maxS) * 100
        if score < 1:
            score = 1
        submission = Submission(user_id=userid, question_id=id, \
                                result=True, result_score=score, result_message="Solved")

        db.session.add(submission)
        db.session.commit()
        db.create_all()
        all_submissions = db.session.query(functions.max(Submission.result_score)).filter(Submission.user_id==userid).group_by(
            Submission.question_id).all()
        user = User.query.filter(User.id == userid).first()
        user.total_score = sum((x[0] for x in all_submissions))
        db.session.commit()
        print("done")


@questions.route('/questions/<int:id>/submit', methods=('GET', 'POST'))
def submit(id):
    """
    similar to the test submission.
    The code is submitted by this method , it stores the code in the `upload` folder and then finds the score
    :param id:
    :return:
    """
    print(current_user.username)
    form = SubmitForm()
    if request.method == 'POST':
        file = request.files['code']
        print(os.path.abspath("static"))
        if file and allowed_file(file.filename):
            filename = "_".join([current_user.username, str(id), str(int(time.time()))])
            location = os.path.join(UPLOAD_LOCATION, filename)
            file.save(location)
            userid = int(current_user.id)
            # code_process = Process(target=find_score, args=(location, id, userid))
            # code_process.start()
            find_score(location,id,userid)
            flash("your code has been uploaded")
            return redirect(url_for("questions.getquestion", id=id))
        else:
            flash("that file format is not allowed", category="warning")
            return redirect(url_for("questions.getquestion", id=id))


@questions.route('/status/')
def status():
    all_submissions = Submission.query.order_by(desc(Submission.submited_on)).all()
    all_users = User.query.all()
    all_users_username = [" "] + [user.username for user in all_users]
    print(all_users_username)

    return render_template("status.html", submissions=all_submissions, allusers=all_users_username)


@questions.route('/submissions/')
@login_required
def status_individual():
    user_submissions = current_user.submissions
    print(user_submissions)
    return render_template("status.html", submissions=user_submissions, ofuser=True)


global_queue = Queue()


def check_similarity(queue, filename1, filename2):
    with open(filename1) as comp_test:
        with open(filename2) as user_test:
            if comp_test.read() == user_test.read():
                queue.put("True")
            else:
                queue.put("False")


@questions.route('/tests/<int:id>', methods=['POST'])
@login_required
def test_check(id):
    '''
    this method takes the test file and saves it to the `tests` folder ,it also spins up a process which stores the
    result in a distributed queue

    TODO - check if multiple requests alienate the queue
    :param id:
    :return:
    '''
    if request.method == "POST":
        selected_question = Question.query.filter(Question.id == id).first()
        filename = selected_question.testcases[0].output_tests
        file_location = os.path.join("app/static/tests", filename)

        test_file_name = "_".join([current_user.username, str(selected_question.id), str(int(time.time()))])
        test_file_name += ".txt"
        test_file = request.files['test']
        location = os.path.join("app/static/tests/user_tests", test_file_name)
        test_file.save(location)

        process = Process(target=check_similarity, args=(global_queue, file_location, location))
        process.start()
        data = global_queue.get()
        process.join()
        return data

app/templates/_question_helper.html
{% set counter = 0 %}

{% for question in all_quest %}


    <td>
        {{ question.id }}
    </td>
    <td>
        <a href="{{ url_for("questions.getquestion",id=question.id) }}">{{ question.title }}</a>
    </td>

        {% if allsubmission[counter] and allsubmission[counter][0] == question.id   %}
            <td>
      {{ allsubmission[counter][1] }}
             </td>

            <td>

                {{ allsubmission[counter][2] }}

            </td>
        {% set counter = counter + 1  %}



        {% else %}
            <td>-</td>
            <td>-</td>
    {% endif %}

</tr>
  {% endfor %}
<tr>

app/templates/_status_row.html
{% for submission in submissions %}
    <tr>
        <td>
            {{ loop.index }}
        </td>
        <td>
            <a href="{{ url_for("questions.getquestion",id=submission.question_id) }}">{{ submission.question_id }}</a>
        </td>
        <td>
            {% if allusers %}
                {{ allusers[submission.user_id] }}
            {% else %}
                {{ current_user.username }}
            {% endif %}
        </td>
        <td>
            {{ submission.result_score }}
        </td>
        <td>
            {{ submission.submited_on }}
        </td>


    </tr>
{% endfor %}

app/templates/_submit_modal.html
{% import "bootstrap/wtf.html" as wtf %}

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Submit code</h4>
            </div>
            <div class="modal-body">
                <div class="upload">

                    {{ wtf.quick_form(test_form,action =url_for("questions.test_check",id=question.id),method="post",enctype="multipart/form-data",extra_classes="test-form") }}
                    <br>
                    <fieldset class="solution" disabled>
                        {{ wtf.quick_form(form,action=url_for("questions.submit",id = question.id),method="post",enctype="multipart/form-data") }}
                    </fieldset>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        // Variable to store your files
        var files;
        // Add events
        $('#test').on('change', prepareUpload);
        $('.test-form').on('submit', uploadFiles);

        // Grab the files and set them to our variable
        function prepareUpload(event) {
            console.log("prepare Upload is working");
            files = event.target.files[0];
        }

        // Catch the form submit and upload the files
        function uploadFiles(event) {
            var solution = $(".solution");
            var formData = new FormData($(".test-form")[0]);
            console.log(formData);
            console.log("inside upload files");
            event.stopPropagation(); // Stop stuff happening
            event.preventDefault(); // Totally stop stuff happening
            var first_input = $(".form-group").first();


            $.ajax({
                url: '{{ url_for("questions.test_check",id=question.id) }}',  //Server script to process data
                type: 'POST',
                xhr: function () {  // Custom XMLHttpRequest
                    var myXhr = $.ajaxSettings.xhr();
                    return myXhr;
                },
                //Ajax events
                success: function (data, a) {
                    if (data == "True") {
                        solution.removeAttr("disabled");
                        first_input.removeClass("has-error");
                        first_input.addClass("has-success");
                    }
                    else {
                        first_input.removeClass("has-success");
                        first_input.addClass("has-error");
                    }

                },
                // Form data
                data: formData,
                //Options to tell jQuery not to process data or worry about content-type.
                cache: false,
                contentType: false,
                processData: false
            })

        }
    });


</script>

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% block html_attribs %} lang="en"{% endblock %}
{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for("static",filename="css/style.css") }}">
    <script src="{{ url_for("static",filename="js/jquery.js")}}" > </script>

      <script src="{{ url_for("static",filename="js/bootstrap.js") }}"></script>

{% endblock %}
{% block title %}{% if not title %}Code golf {% else %}{{ title }}{% endif %} {% endblock %}
{% block navbar %}
    <nav class="navbar-fixed-top navbar">
        <div class="container-fluid" style="background-color: lavender;">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="{{ url_for("questions.index") }}">{% if not title %}Questions {% else %}
                    {{ title }}{% endif %}</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for("questions.status") }}">Status</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-expanded="false">Hello, {{ current_user.username }} <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url_for("questions.status_individual") }}">My submissions</a></li>

                                <li><a href="{{ url_for("auth.logout") }}">Logout</a></li>

                            </ul>
                        </li>

                    {% else %}
                        <li><a href="{{ url_for("auth.login") }}">LOGIN</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
        {% for category,message in get_flashed_messages(with_categories=True) %}
            {% if category=="message" %}
                <div class="alert alert-success">
            {% else %}
                <div class="alert alert-{{ category }}">
            {% endif %}

        <button type="button" class="close" data-dismiss="alert">X</button>
        {{ message }}
        </div>

        {% endfor %}

    </nav>
{% endblock %}

app/templates/index.html
{% extends "login.html" %}

{% block form_header %}
    Questions
{% endblock %}
{% block form %}
    <table class="table table-bordered table-hover table-responsive">
        <thead>
        <tr>
            <th>#</th>
            <th>Question name</th>
            <th>score</th>
            <th>result</th>
        </tr>
        </thead>
        <tbody>
           {% include "_question_helper.html" %}

        </tbody>
    </table>

{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
    <div class="container-fluid fontsize">
        <div style="margin-top:90px ">
            <div class="row-fluid">
                <div class="page-header"><h2 style="margin: 5px 5px 5px 5px;">{% block form_header %}
                    Login{% endblock %}</h2></div>
            </div>
        </div>
        <div style="padding: 20px 10px 10px 10px;margin: 0 auto;">
            <div class="container-fluid">
                <div class="col-md-8 cliente fontsize" style="height:100vh;">

                    {% block form %}
                        {{ wtf.quick_form(forms) }}
                        <br>
                        <p style="display: inline;float: left">Haven't registered yet? </p>
                        <a style="margin: 10px 10px 10px 10px" href="{{ url_for("auth.register") }}"> Register</a>
                    {% endblock %}

                </div>
                <div class="col-md-3 cliente" style="height:100vh;">
                    {% block aside %}
                        {% if current_user.is_authenticated %}
                            <div style="float:right"><h2>Score : {{ current_user.total_score | float }}</h2></div>
                        {% endif %}
                    {% endblock %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/question.html
{% extends "login.html" %}
{% block form_header %}
    {{ question.title }}
{% endblock %}
{% block form %}
    <h3>Description</h3>
    <br>
    <p>{{ question.description | safe }} </p>
    <br>
    <h3>input format:</h3>
    <br>
    <p>{{ question.inputformat | safe }}</p>
    <br>

    <h3>Constraints :</h3>
    <p>
        {{ question.constraint | safe }}
    </p>
    <br>
    <h3>Sample Input:</h3>
    <pre>{{ question.test_input }}
    </pre>
    <h3>Sample Output:</h3>
    <pre>{{ question.test_output }}
    </pre>

    <br>
    <a href="http://10.1.10.154:9090/static/tests/{{file_name}}" > Download </a>
    <blockquote style="font-family: 'lucida console';font-size: 10px">added on {{ question.added_on }}</blockquote>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
        submit
    </button>
    <br>
    <br>

    {% include "_submit_modal.html" %}
    <br>


{% endblock %}

app/templates/register.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "login.html" %}
{% block form_header %}
    Register
{% endblock %}
{% block form %}
    {{ wtf.quick_form(form,action=url_for("auth.register"),method="post") }}
{% endblock %}

app/templates/status.html
{% extends "login.html" %}

{% block form_header %}
    {% if ofuser %}
        {{ current_user.username }}'s Submissions
    {% else %}
        All Submissions
    {% endif %}
{% endblock %}
{% block form %}
    <table class="table table-bordered table-hover table-responsive">
        <thead>
        <tr>
            <th>#</th>
            <th>Question id</th>
            <th>user</th>
            <th>result</th>
            <th>submitted on</th>
        </tr>
        </thead>
        <tbody>
        {% include "_status_row.html" %}
        </tbody>

    </table>

{% endblock %}